---
engines:
  coffeelint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
    checks:
      QualifyingElement:
        enabled: false
ratings:
  paths:
  - "**.scss"
  - "**.coffee"
exclude_paths: []
