// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    var SOURCES;

    SOURCES = {
      DOCS: {
        PRIVATE: ['src/**/*.coffee', 'README.md']
      }
    };
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      bower: {
        install: {
          options: {
            cleanBowerDir: true,
            cleanTargetDir: false,
            copy: true,
            install: true,
            layout: function(type, component) {
              return '';
            },
            targetDir: 'lib',
            verbose: true
          }
        }
      },
      groc: {
        "private": SOURCES.DOCS.PRIVATE,
        options: {
          out: 'docs',
          'repository-url': 'https://bitbucket.org/hlfcoding/morning-stroll'
        }
      },
      watch: {
        docs: {
          files: SOURCES.DOCS.PRIVATE,
          tasks: ['groc:private'],
          options: {
            spawn: false
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-bower-task');
    grunt.loadNpmTasks('grunt-groc');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.registerTask('default', []);
    return grunt.registerTask('docs', ['groc', 'watch:docs']);
  };

}).call(this);
