// Generated by CoffeeScript 1.6.2
(function() {
  requirejs.config({
    baseUrl: 'lib',
    paths: {
      app: '../release'
    }
  });

  requirejs(['phaser', 'app/game'], function(Phaser, MorningStroll) {
    'use strict';
    var game;

    window.DEBUG = true;
    game = new MorningStroll();
    game.start();
    console.info(game);
    if (window.DEBUG === true) {
      window.Phaser = Phaser;
      return window.game = game;
    }
  });

}).call(this);
