// Generated by CoffeeScript 1.6.1
(function() {

  requirejs.config({
    baseUrl: 'lib',
    paths: {
      app: '../release'
    },
    shim: {
      'phaser': {
        deps: []
      }
    }
  });

  requirejs(['app/game', 'phaser'], function(MorningStroll) {
    'use strict';
    var game;
    window.DEBUG = true;
    game = new MorningStroll();
    game.start();
    return console.info(game);
  });

}).call(this);
