// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['phaser'], function(Phaser) {
    var C, Player, Sprite, _ref;

    Sprite = Phaser.Sprite;
    Player = (function(_super) {
      __extends(Player, _super);

      function Player() {
        _ref = Player.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      return Player;

    })(Sprite);
    return C = Player;
  });

}).call(this);
