// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['phaser'], function() {
    var C, PlayState;
    PlayState = (function(_super) {

      __extends(PlayState, _super);

      function PlayState() {
        return PlayState.__super__.constructor.apply(this, arguments);
      }

      PlayState.prototype._platform = null;

      PlayState.prototype._fallChecking = void 0;

      PlayState.FLOOR_HEIGHT = 32;

      PlayState.PLAYER_WIDTH = 72;

      PlayState.PLAYER_HEIGHT = 72;

      PlayState.prototype._player = null;

      PlayState.prototype._mate = null;

      PlayState.prototype.create = function() {};

      return PlayState;

    })(Phaser.State);
    return C = PlayState;
  });

}).call(this);
